[phases.setup]
nixPkgs = ["python312", "postgresql"]
pythonVersion = "3.12"

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["cd api && alembic upgrade head"]

[start]
cmd = "cd api && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
